In [2]:
import cv2
import numpy as np

In [23]:
white_canvas = np.zeros((500,500,3) , dtype='uint8') + 255 # 흰 캔버스 생성
cat = cv2.imread('C:\\numpyandOpenCv\opencv\\assets\images\cat.jpg')

In [24]:
cv2.line(
    white_canvas, # 이미지(캔버스)
    (20,20), # 시작점 (x1, y1)
    (250, 250), # 끝점
    (255,0,0), # 선 색상(BGR 형식)
    3, # 선 두께
    cv2.LINE_AA # 선 유형(여기서는 안티앨리어싱)
)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [25]:
cv2.line(white_canvas,(250,250),(0,500), (0,0,255), 3 , cv2.LINE_AA)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 55,  55, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [26]:
# 원 그리기
cv2.circle(white_canvas, (250,250) , 150 , (0 , 255 , 0) , 3 , cv2.LINE_AA)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 55,  55, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [27]:
# 네모 그리기
cv2.rectangle(white_canvas, (50,50) , (200, 200) , (0,0,0) , 2, cv2.LINE_AA)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 55,  55, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [36]:
# 고양이 이미지에 네모 그리기
cv2.rectangle(cat, (145,65) , (425,425) , (0,0,0) , 2 , cv2.LINE_AA)

array([[[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       ...,

       [[162, 169, 172],
        [162, 169, 172],
        [162, 169, 172],
        ...,
        [203, 206, 184],
        [204, 207, 185],
        [204, 207, 185]],

       [[164, 171, 174],
        [164, 171, 174],
        [164, 171, 174],
        ...,
        [203, 206, 184],
        [203, 206, 184],
        [204, 207, 185]],

       [[165, 172, 175],
        [165, 172, 175],
        [165, 172, 175],
        ...,
        [202, 205, 183],
        [202, 205, 183],
        [203, 206, 184]]

In [39]:
# 고양이 이미지에 다른 네모 그리기
cv2.rectangle(cat, (10,10,300,200) , (255,0,0) , 3 , cv2.LINE_AA)

array([[[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       ...,

       [[162, 169, 172],
        [162, 169, 172],
        [162, 169, 172],
        ...,
        [203, 206, 184],
        [204, 207, 185],
        [204, 207, 185]],

       [[164, 171, 174],
        [164, 171, 174],
        [164, 171, 174],
        ...,
        [203, 206, 184],
        [203, 206, 184],
        [204, 207, 185]],

       [[165, 172, 175],
        [165, 172, 175],
        [165, 172, 175],
        ...,
        [202, 205, 183],
        [202, 205, 183],
        [203, 206, 184]]

In [41]:
# 고양이 이미지에 텍스트 추가
cv2.putText(cat, 'Cat' , (300,300) , cv2.FONT_HERSHEY_SIMPLEX , 1 , (0,255,0) , 2)

array([[[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [165, 115,  25],
        [165, 115,  25],
        [165, 115,  25]],

       ...,

       [[162, 169, 172],
        [162, 169, 172],
        [162, 169, 172],
        ...,
        [203, 206, 184],
        [204, 207, 185],
        [204, 207, 185]],

       [[164, 171, 174],
        [164, 171, 174],
        [164, 171, 174],
        ...,
        [203, 206, 184],
        [203, 206, 184],
        [204, 207, 185]],

       [[165, 172, 175],
        [165, 172, 175],
        [165, 172, 175],
        ...,
        [202, 205, 183],
        [202, 205, 183],
        [203, 206, 184]]

In [42]:
cv2.imshow('image', cat)
cv2.waitKey()
cv2.destroyAllWindows()